FROM node:16-alpine

WORKDIR /frontend
COPY ./frontend/package*.json ./
RUN npm install
COPY ./frontend /frontend
RUN npm run build


FROM nginx-alpine
COPY --from=0 /frontend/build /usr/share/nginx/html
COPY ./frontend/nginx.conf /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]
EXPOSE 80