version: '3.1'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      .env
    depends_on:
      - mongodb
    networks:
      - my-network
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my-network


  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    env_file:
      .env 
    volumes:
      - ~/data:/data/db
    networks:
      - my-network


networks:
  my-network:
    driver: bridge